[workspace]
resolver = "2"
members = ["song-guessr-server"]

[profile.release]
lto = true

[workspace.lints.clippy]
pedantic = { level = "deny" }
perf = { level = "warn" }
style = { level = "warn" }
complexity = { level = "warn" }
