[package]
name = "song-guessr-server"
version = "0.1.0"
authors = ["Thang Pham <phamducthang1234@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.95"
axum = "0.7.9"
chrono = "0.4.39"
librespot-core = "0.6.0"
librespot-oauth = "0.6.0"
rspotify = "0.13.3"
tokio = { version = "1.41.1", features = [
  "rt",
  "rt-multi-thread",
  "macros",
  "time",
] }
tower-http = { version = "0.6.2", features = ["cors"] }
